# Uncomment the next line to define a global platform for your project
#  platform :ios, '14.0'

target 'PokeJournaliOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '14.1'

  # Pods for PokeJournaliOS
  pod 'network', :path => '../../data/network'
  
  target 'PokeJournaliOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeJournaliOSUITests' do
    # Pods for testing
  end

end
